version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://127.0.0.1:3001/api
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - SURREALDB_URL=http://surrealdb:8000
    depends_on:
      surrealdb:
        condition: service_healthy

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: start --user root --pass root memory
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
    healthcheck:
      test: ["CMD", "/surreal", "isready"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  default:
    name: studentvoice_network
