# Use an official Node runtime as the parent image
FROM node:18 as runner

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the app
RUN npm run build:frontend

# Expose port
EXPOSE 3001

# Run the server
CMD ["npm", "run", "start:frontend"]

