# Use an official Node runtime as the parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the server directory contents into the container at /app
COPY server ./

# Install dependencies
RUN npm install

# Install TypeScript globally
RUN npm install -g typescript

# Compile TypeScript to JavaScript
RUN npm run build

# Expose port
EXPOSE 3001

# Run the server
CMD ["npm", "run", "start"]